version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "carly-html-report-generator"
s3_bucket = "carly-lambda-deploy-staging"
s3_prefix = "html-report-generator"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"

[production.deploy.parameters]
stack_name = "carly-html-report-generator"
s3_bucket = "carly-lambda-deploy-production"
s3_prefix = "html-report-generator"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
